<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\ProductImage;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Sản phẩm phòng ngủ
            [
                'name' => 'Giường ngủ hiện đại',
                'description' => 'Giường ngủ hiện đại với thiết kế đơn giản, có ngăn kéo tích hợp để cất đồ. Hoàn hảo cho phòng ngủ hiện đại.',
                'section_id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'material_id' => 1,
                'price' => 15900000, // 15.9 triệu VND
                'sale_price' => 12900000, // 12.9 triệu VND
                'stock' => 15,
                'slug' => 'giuong-ngu-hien-dai',
                'featured' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Tủ quần áo gỗ sồi',
                'description' => 'Tủ quần áo rộng rãi bằng gỗ sồi với cửa trượt và hệ thống tổ chức nội thất.',
                'section_id' => 1,
                'category_id' => 2,
                'brand_id' => 2,
                'material_id' => 1,
                'price' => 22900000, // 22.9 triệu VND
                'sale_price' => null,
                'stock' => 8,
                'slug' => 'tu-quan-ao-go-soi',
                'featured' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Bàn đầu giường tối giản',
                'description' => 'Bàn đầu giường sạch sẽ và đơn giản với ngăn kéo và kệ mở cho các vật dụng cần thiết.',
                'section_id' => 1,
                'category_id' => 3,
                'brand_id' => 3,
                'material_id' => 2,
                'price' => 5200000, // 5.2 triệu VND
                'sale_price' => 4200000, // 4.2 triệu VND
                'stock' => 25,
                'slug' => 'ban-dau-giuong-toi-gian',
                'featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Tủ trang điểm cổ điển',
                'description' => 'Tủ trang điểm phong cách cổ điển với sáu ngăn kéo và phần cứng trang nhã.',
                'section_id' => 1,
                'category_id' => 4,
                'brand_id' => 4,
                'material_id' => 3,
                'price' => 11900000, // 11.9 triệu VND
                'sale_price' => null,
                'stock' => 12,
                'slug' => 'tu-trang-diem-co-dien',
                'featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Bộ nội thất phòng ngủ hoàn chỉnh',
                'description' => 'Bộ nội thất phòng ngủ hoàn chỉnh bao gồm giường, tủ quần áo, bàn đầu giường và tủ trang điểm.',
                'section_id' => 1,
                'category_id' => 5,
                'brand_id' => 5,
                'material_id' => 1,
                'price' => 49900000, // 49.9 triệu VND
                'sale_price' => 39900000, // 39.9 triệu VND
                'stock' => 5,
                'slug' => 'bo-noi-that-phong-ngu-hoan-chinh',
                'featured' => true,
                'status' => 'active',
            ],

            // Sản phẩm phòng khách
            [
                'name' => 'Sofa góc chữ L',
                'description' => 'Sofa góc chữ L thoải mái hoàn hảo cho các buổi tụ tập gia đình và thư giãn.',
                'section_id' => 2,
                'category_id' => 6,
                'brand_id' => 1,
                'material_id' => 7,
                'price' => 31900000, // 31.9 triệu VND
                'sale_price' => 25900000, // 25.9 triệu VND
                'stock' => 10,
                'slug' => 'sectional-sofa',
                'featured' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Glass Coffee Table',
                'description' => 'Modern glass coffee table with metal legs and tempered glass top.',
                'section_id' => 2,
                'category_id' => 7,
                'brand_id' => 5,
                'material_id' => 3,
                'price' => 499.99,
                'sale_price' => null,
                'stock' => 20,
                'slug' => 'glass-coffee-table',
                'featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Entertainment Center',
                'description' => 'Large entertainment center with space for TV, gaming consoles, and media storage.',
                'section_id' => 2,
                'category_id' => 6,
                'brand_id' => 2,
                'material_id' => 1,
                'price' => 899.99,
                'sale_price' => 749.99,
                'stock' => 7,
                'slug' => 'entertainment-center',
                'featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Floating Bookshelf',
                'description' => 'Modern floating bookshelf system for displaying books and decorative items.',
                'section_id' => 2,
                'category_id' => 1,
                'brand_id' => 3,
                'material_id' => 1,
                'price' => 199.99,
                'sale_price' => null,
                'stock' => 30,
                'slug' => 'floating-bookshelf',
                'featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Living Room Set',
                'description' => 'Complete living room set including sofa, coffee table, and entertainment center.',
                'section_id' => 2,
                'category_id' => 5,
                'brand_id' => 2,
                'material_id' => 6,
                'price' => 3299.99,
                'sale_price' => 2799.99,
                'stock' => 3,
                'slug' => 'living-room-set',
                'featured' => true,
                'status' => 'active',
            ],

            // Dining Room Products
            [
                'name' => 'Farmhouse Dining Table',
                'description' => 'Rustic farmhouse dining table seating up to 8 people with distressed finish.',
                'section_id' => 3,
                'category_id' => 2,
                'brand_id' => 1,
                'material_id' => 1,
                'price' => 1199.99,
                'sale_price' => 999.99,
                'stock' => 6,
                'slug' => 'farmhouse-dining-table',
                'featured' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Upholstered Dining Chairs',
                'description' => 'Comfortable upholstered dining chairs with fabric seats and wooden frames.',
                'section_id' => 3,
                'category_id' => 4,
                'brand_id' => 4,
                'material_id' => 6,
                'price' => 149.99,
                'sale_price' => null,
                'stock' => 40,
                'slug' => 'upholstered-dining-chairs',
                'featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Modern Sideboard',
                'description' => 'Sleek modern sideboard with drawers and cabinet storage for dining room essentials.',
                'section_id' => 3,
                'category_id' => 5,
                'brand_id' => 3,
                'material_id' => 1,
                'price' => 799.99,
                'sale_price' => 649.99,
                'stock' => 9,
                'slug' => 'modern-sideboard',
                'featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Complete Dining Set',
                'description' => 'Complete dining room set including table, 6 chairs, and matching sideboard.',
                'section_id' => 3,
                'category_id' => 4,
                'brand_id' => 2,
                'material_id' => 1,
                'price' => 2199.99,
                'sale_price' => 1899.99,
                'stock' => 4,
                'slug' => 'complete-dining-set',
                'featured' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Bar Height Stools',
                'description' => 'Adjustable bar height stools with comfortable seats and footrests.',
                'section_id' => 3,
                'category_id' => 6,
                'brand_id' => 5,
                'material_id' => 4,
                'price' => 199.99,
                'sale_price' => null,
                'stock' => 25,
                'slug' => 'bar-height-stools',
                'featured' => false,
                'status' => 'active',
            ],

            // Home Office Products
            [
                'name' => 'Executive Desk',
                'description' => 'Large executive desk with drawers and cable management for professional workspace.',
                'section_id' => 4,
                'category_id' => 6,
                'brand_id' => 1,
                'material_id' => 1,
                'price' => 1299.99,
                'sale_price' => 1099.99,
                'stock' => 8,
                'slug' => 'executive-desk',
                'featured' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Ergonomic Office Chair',
                'description' => 'High-quality ergonomic office chair with lumbar support and adjustable features.',
                'section_id' => 4,
                'category_id' => 7,
                'brand_id' => 2,
                'material_id' => 5,
                'price' => 599.99,
                'sale_price' => null,
                'stock' => 15,
                'slug' => 'ergonomic-office-chair',
                'featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Filing Cabinet',
                'description' => 'Two-drawer filing cabinet with lock for secure document storage.',
                'section_id' => 4,
                'category_id' => 6,
                'brand_id' => 3,
                'material_id' => 5,
                'price' => 299.99,
                'sale_price' => 249.99,
                'stock' => 20,
                'slug' => 'filing-cabinet',
                'featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Office Storage Unit',
                'description' => 'Modular office storage unit with shelves, drawers, and cabinet space.',
                'section_id' => 4,
                'category_id' => 4,
                'brand_id' => 4,
                'material_id' => 1,
                'price' => 699.99,
                'sale_price' => null,
                'stock' => 12,
                'slug' => 'office-storage-unit',
                'featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Complete Office Set',
                'description' => 'Complete home office set including desk, chair, filing cabinet, and storage unit.',
                'section_id' => 4,
                'category_id' => 2,
                'brand_id' => 5,
                'material_id' => 1,
                'price' => 2499.99,
                'sale_price' => 2199.99,
                'stock' => 3,
                'slug' => 'complete-office-set',
                'featured' => true,
                'status' => 'active',
            ],

            // Outdoor Products
            [
                'name' => 'Patio Dining Set',
                'description' => 'Weather-resistant patio dining set with table and 4 chairs for outdoor entertaining.',
                'section_id' => 5,
                'category_id' => 5,
                'brand_id' => 4,
                'material_id' => 1,
                'price' => 899.99,
                'sale_price' => 749.99,
                'stock' => 10,
                'slug' => 'patio-dining-set',
                'featured' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Garden Bench',
                'description' => 'Classic wooden garden bench perfect for outdoor relaxation and garden decoration.',
                'section_id' => 5,
                'category_id' => 2,
                'brand_id' => 2,
                'material_id' => 1,
                'price' => 399.99,
                'sale_price' => null,
                'stock' => 18,
                'slug' => 'garden-bench',
                'featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Outdoor Coffee Table',
                'description' => 'Weather-resistant outdoor coffee table with tempered glass top and metal frame.',
                'section_id' => 5,
                'category_id' => 3,
                'brand_id' => 1,
                'material_id' => 3,
                'price' => 299.99,
                'sale_price' => 249.99,
                'stock' => 15,
                'slug' => 'outdoor-coffee-table',
                'featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Adirondack Chairs',
                'description' => 'Classic Adirondack chairs made from weather-resistant materials for outdoor comfort.',
                'section_id' => 5,
                'category_id' => 4,
                'brand_id' => 2,
                'material_id' => 1,
                'price' => 199.99,
                'sale_price' => null,
                'stock' => 25,
                'slug' => 'adirondack-chairs',
                'featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Outdoor Storage Box',
                'description' => 'Weather-resistant outdoor storage box for cushions, gardening tools, and outdoor accessories.',
                'section_id' => 5,
                'category_id' => 5,
                'brand_id' => 3,
                'material_id' => 6,
                'price' => 149.99,
                'sale_price' => 129.99,
                'stock' => 20,
                'slug' => 'outdoor-storage-box',
                'featured' => false,
                'status' => 'active',
            ],
        ];

        foreach ($products as $productData) {
            $product = Product::create($productData);
            
            // Add sample images for each product
            ProductImage::create([
                'product_id' => $product->id,
                'url' => 'products/product-' . $product->id . '-1.jpg',
                'alt_text' => $product->name . ' - Main View',
                'is_primary' => true,
                'sort_order' => 1,
            ]);
            
            ProductImage::create([
                'product_id' => $product->id,
                'url' => 'products/product-' . $product->id . '-2.jpg',
                'alt_text' => $product->name . ' - Detail View',
                'is_primary' => false,
                'sort_order' => 2,
            ]);
        }
    }
}